version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            echo "Start deploy"
  enterprise:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Setup Stage
          command: |
            if [ ${{ github.event.label.name }} == 'enterprise' ]
            then
              echo 'export STAGE=enterprise' >> ~/.bashrc
            fi
      - run:
          name: Run Deployment
          command: |
            source ~/.bashrc
            echo $STAGE

  voyager:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Setup Stage
          command: |
            sudo apt -y update || true
            echo 'export STAGE=voyager' >> ~/.bashrc
      - run:
          name: Run Deployment
          command: |
            source ~/.bashrc
            echo $STAGE

workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - test
