version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@107.20.31.33 \
            "echo Start deploy && \
            cd ~/laravelDemo && \
            git pull origin master && \
            cp .env.example .env && \
            sudo docker compose up --build -d && \
            echo Deploy end"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
