version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            "echo Start deploy"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
