version: 2
on:
  pull_request:
    types:
      - labeled
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@107.20.31.33 \
            "echo Start deploy && \
            cd ~/laravelDemo && \
            git pull origin master && \
            cp .env.example .env && \
            sudo docker compose up --build -d && \
            echo Deploy end"
  labeled:
    if: github.event.label.name == 'enterprise'
    machine:
      image: ubuntu-2004:202107-02
      steps:
        - checkout
        - run:
            name: Setup Stage
            command: |
              echo "Enterprise"

workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
      filters:
        branches:
          only:
            - master
