version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.176.69.77
