# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to AWS

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - labeled

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    env:
      CI: false
    container:
      image: leapfrogtechnology/envault:0.4.6-node10.16.0-stretch-slim

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Stage
      env:
        CI: false
      shell: bash
      run: |
        touch .bashrc
        if [ $GITHUB_REF_NAME == "master" ]
        then
          echo "export STAGE=master" >> .bashrc
        elif [ $GITHUB_REF_NAME == "mike" ]
        then
          echo 'export STAGE=mike' >> .bashrc
        elif [ ${{ github.event.label.name }} == 'enterprise' ]
        then
          echo 'export STAGE=enterprise' >> .bashrc
        elif [ ${{ github.event.label.name }} == 'voyager' ]
        then
          echo 'export STAGE=voyager' >> .bashrc
        elif [ ${{ github.event.label.name }} == 'cerritos' ]
        then
          echo 'export STAGE=cerritos' >> .bashrc
        else
          echo 'export STAGE=dirty' >> .bashrc
        fi

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run Deployment
      run: |
        . ./.bashrc
        echo $STAGE




