# run the workflow on each push to labeled PR
name: Appealio-API Workflow
on:
  pull_request:
    types:
      - synchronize
jobs:
  checkLabels:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.labels.*.name[0] }}
    steps:
      - name: Check Label
        run: |
          echo LABELS should not be empty

  runDeployment:
    needs: [checkLabels]
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
        exclude:
          label:
            - DO NOT MERGE

    name: Deployment for ${{ matrix.label }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Stage Setup
      - name: Setup Stage
        shell: bash
        run: |
#          sudo apt -y update || true
          echo 'export STAGE="${{ matrix.label }}"' >> ~/.bash_profile

      # Login
#      - name: Login to AWS
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy Services
      - name: Deploy Services to AWS
        shell: bash
        run: |
          source ~/.bash_profile
          echo $STAGE
#          chmod +x deploy/deploy.sh
#          deploy/deploy.sh $STAGE

      # send notifications to slack channel
      - name: Notify Slack Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Build Succeed :rocket:'
          SLACK_USERNAME: 'GitHub_Actions'
          SLACK_ICON: https://docvocate.com/assets/img/logo.png
          SLACK_COLOR: 'good'

      - name: Notify Slack Fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Build Failed :x:'
          SLACK_USERNAME: 'GitHub_Actions'
          SLACK_ICON: https://docvocate.com/assets/img/logo.png
          SLACK_COLOR: '#F32013'
