# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to AWS

on:
  push:
    branches: [ "master" ]

#env:
#  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Stage
#      working-directory: /home/runner/work/
      run: |
        sudo apt -y update || true
        touch .bashrc
        cat /home/runner/.bashrc >> .bashrc
        ls -al .bashrc
        ls -al /home/runner/.bashrc
        if [ $GITHUB_REF_NAME == "master" ];
        then
          echo "export STAGE=master" >> .bashrc
        elif [ $GITHUB_REF_NAME == "mike" ];
        then
          echo 'export STAGE=mike' >> .bashrc
        else
          echo 'export STAGE=dirty' >> .bashrc
        fi
      shell: bash
    - name: Run Deployment
      run: |
        source .bashrc
        chmod +x deploy.sh
        ./deploy.sh $STAGE
        rm .bashrc
      shell: bash


#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ env.AWS_REGION }}


