name: approved workflow
on:
  pull_request:
   types:
    - labeled
jobs:
  enterprise:
    if: github.event.label.name == 'enterprise'
    runs-on: ubuntu-latest
    name: Deploy to QA environment
    steps:
    - uses: actions/checkout@v2
    - name: a simple circle-ci deployment trigger
      id: curl-circle-ci
      uses: Open-Source-Contrib/circle-ci-trigger-action@latest
      with:
        circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}
        circle_ci_job: ${{ secrets.ENTERPRISE }}
        circle_ci_project_url: ${{ github.event.pull_request.head.ref }}
    # Use the output from the `hello` step
    - name: Get the output response
      run: echo "The response was ${{ steps.curl-circle-ci.outputs.response }}"

  voyager:
    if: github.event.label.name == 'voyager'
    runs-on: ubuntu-latest
    name: Deploy to QA environment
    steps:
      - uses: actions/checkout@v2
      - name: a simple circle-ci deployment trigger
        id: curl-circle-ci
        uses: Open-Source-Contrib/circle-ci-trigger-action@latest
        with:
          circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}
          circle_ci_job: ${{ secrets.VOYAGER }}
          circle_ci_project_url: ${{ github.event.pull_request.head.ref }}
