# This is a basic workflow to help you get started with Actions

name: CI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: On EC2
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy to my EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.176.106.254
          username: ec2-user
          key: ${{ secrets.SSHKEY }}       
          port: 22
          script: |
            echo Start deploy
            cd ~/laravelDemo/
            git pull origin master
            cp .env.example .env
            sudo docker compose up --build -d
            echo Deploy end

